/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyllabusRouteImport } from './routes/syllabus'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContentsRouteImport } from './routes/contents'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as ChapterSlugRouteImport } from './routes/chapter.$slug'
import { Route as BookChapterSlugRouteImport } from './routes/book.$chapterSlug'
import { Route as BookSearchIndexRouteImport } from './routes/book.search.index'

const SyllabusRoute = SyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsRoute = ContentsRouteImport.update({
  id: '/contents',
  path: '/contents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterSlugRoute = ChapterSlugRouteImport.update({
  id: '/chapter/$slug',
  path: '/chapter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookChapterSlugRoute = BookChapterSlugRouteImport.update({
  id: '/book/$chapterSlug',
  path: '/book/$chapterSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSearchIndexRoute = BookSearchIndexRouteImport.update({
  id: '/book/search/',
  path: '/book/search/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/contents': typeof ContentsRoute
  '/dashboard': typeof DashboardRoute
  '/syllabus': typeof SyllabusRoute
  '/book/$chapterSlug': typeof BookChapterSlugRoute
  '/chapter/$slug': typeof ChapterSlugRoute
  '/book/': typeof BookIndexRoute
  '/book/search/': typeof BookSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/contents': typeof ContentsRoute
  '/dashboard': typeof DashboardRoute
  '/syllabus': typeof SyllabusRoute
  '/book/$chapterSlug': typeof BookChapterSlugRoute
  '/chapter/$slug': typeof ChapterSlugRoute
  '/book': typeof BookIndexRoute
  '/book/search': typeof BookSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/author': typeof AuthorRoute
  '/contents': typeof ContentsRoute
  '/dashboard': typeof DashboardRoute
  '/syllabus': typeof SyllabusRoute
  '/book/$chapterSlug': typeof BookChapterSlugRoute
  '/chapter/$slug': typeof ChapterSlugRoute
  '/book/': typeof BookIndexRoute
  '/book/search/': typeof BookSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/author'
    | '/contents'
    | '/dashboard'
    | '/syllabus'
    | '/book/$chapterSlug'
    | '/chapter/$slug'
    | '/book/'
    | '/book/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/author'
    | '/contents'
    | '/dashboard'
    | '/syllabus'
    | '/book/$chapterSlug'
    | '/chapter/$slug'
    | '/book'
    | '/book/search'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/author'
    | '/contents'
    | '/dashboard'
    | '/syllabus'
    | '/book/$chapterSlug'
    | '/chapter/$slug'
    | '/book/'
    | '/book/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthorRoute: typeof AuthorRoute
  ContentsRoute: typeof ContentsRoute
  DashboardRoute: typeof DashboardRoute
  SyllabusRoute: typeof SyllabusRoute
  BookChapterSlugRoute: typeof BookChapterSlugRoute
  ChapterSlugRoute: typeof ChapterSlugRoute
  BookIndexRoute: typeof BookIndexRoute
  BookSearchIndexRoute: typeof BookSearchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/syllabus': {
      id: '/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof SyllabusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents': {
      id: '/contents'
      path: '/contents'
      fullPath: '/contents'
      preLoaderRoute: typeof ContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$slug': {
      id: '/chapter/$slug'
      path: '/chapter/$slug'
      fullPath: '/chapter/$slug'
      preLoaderRoute: typeof ChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$chapterSlug': {
      id: '/book/$chapterSlug'
      path: '/book/$chapterSlug'
      fullPath: '/book/$chapterSlug'
      preLoaderRoute: typeof BookChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/search/': {
      id: '/book/search/'
      path: '/book/search'
      fullPath: '/book/search/'
      preLoaderRoute: typeof BookSearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthorRoute: AuthorRoute,
  ContentsRoute: ContentsRoute,
  DashboardRoute: DashboardRoute,
  SyllabusRoute: SyllabusRoute,
  BookChapterSlugRoute: BookChapterSlugRoute,
  ChapterSlugRoute: ChapterSlugRoute,
  BookIndexRoute: BookIndexRoute,
  BookSearchIndexRoute: BookSearchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
